name: 'Action to build and deploy artifact'
description: 'Build and deploy mulesoft artifact'
author: 'Muzammal Nazir'

inputs:
  release-tag:
    description: 'Release tag name'
    required: true
  cloudhub-envs:
    description: 'Comma separated list of cloudhub environments'
    required: true
  cloudhub-app-name-pattern:
    description: 'Cloudhub application name pattern'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'